The standard Landsat 8 products provided by the USGS EROS Center consist of quantized and calibrated scaled Digital Numbers (DN) representing multispectral image data acquired by both the Operational Land Imager (OLI) and Thermal Infrared Sensor (TIRS).  

The products are delivered in 16-bit unsigned integer format and can be rescaled to the Top Of Atmosphere (TOA) radiance using radiometric rescaling coefficients provided in the product metadata file (MTL file), as described below.

OLI and TIRS band data can be converted to TOA spectral radiance using the radiance rescaling factors provided in the metadata file: 

$${ L }_{ \lambda  }={ M }{ L }{ Q }{ cal }+{ A }{ L }$$

where:              

\\( { L }_{ \lambda  } \\) = TOA spectral radiance (Watts/( m2 * srad * μm))

\\( { M }{ L } \\) = Band-specific multiplicative rescaling factor from the metadata (RADIANCE_MULT_BAND_x, where x is the band number)

\\( { A }{ L } \\) = Band-specific additive rescaling factor from the metadata (RADIANCE_ADD_BAND_x, where x is the band number)

\\( { Q }{ cal } \\) = Quantized and calibrated standard product pixel values (DN)  

### Example

Calculate the TOA radiance of the blue band

```coffee
library(rLandsat8)

setwd("~/Downloads")
product  <- "LC82040322013219LGN00"
l <- ReadLandsat8(product)

radiance.blue <- ToTOARadiance(landsat8=l, band="blue")
```
